name: chem277b
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyterlab
  - notebook
  - nbclassic
  - ipywidgets
  - jupytext
  - ipykernel
  - nbconvert
  - jupyterlab_widgets
  - ipympl
  - plotly
  - bqplot
  - voila
  - panel
  - opencv
  - umap-learn
  - cmake
  - ninja
  - pybind11
  - flask
  - biopython
  - fasta
  - pyclustering
  - nltk
  - multiprocess
  - pip
  - pip:
      - jarvis-tools
